SELECT
    B.AUTHOR_ID AS AUTHOR_ID,
    A.AUTHOR_NAME AS AUTHOR_NAME,
    B.CATEGORY AS CATEGORY,
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN (
    SELECT BOOK_ID, SUM(SALES) SALES
    FROM BOOK_SALES 
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
) AS S ON B.BOOK_ID = S.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC