SELECT DISTINCT A.CART_ID
FROM CART_PRODUCTS A
WHERE 
    EXISTS (
        SELECT 1
        FROM CART_PRODUCTS B
        WHERE B.NAME = 'Milk' AND A.CART_ID = B.CART_ID
    ) AND 
    EXISTS (
        SELECT 1
        FROM CART_PRODUCTS B
        WHERE B.NAME = 'Yogurt' AND A.CART_ID = B.CART_ID
    )
ORDER BY CART_ID