SELECT
    A.FOOD_TYPE,
    A.REST_ID,
    A.REST_NAME,
    A.FAVORITES
FROM 
    REST_INFO A RIGHT JOIN
    (
        SELECT FOOD_TYPE, MAX(FAVORITES) F
        FROM REST_INFO 
        GROUP BY FOOD_TYPE
    ) B
ON A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.F 
ORDER BY A.FOOD_TYPE DESC