SELECT 
    HISTORY.HISTORY_ID,
    CASE
        WHEN DISCOUNT_RATE IS NULL THEN DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1)
        ELSE DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * (1 - DISCOUNT_RATE*0.01)
    END AS FEE
FROM (
    SELECT
        HISTORY_ID,
        CAR_ID,
        START_DATE,
        END_DATE,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) HISTORY
JOIN CAR_RENTAL_COMPANY_CAR CAR
    ON CAR.CAR_ID = HISTORY.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
    ON CAR.CAR_TYPE = PLAN.CAR_TYPE
    AND HISTORY.DURATION_TYPE = PLAN.DURATION_TYPE
WHERE CAR.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY.HISTORY_ID DESC