SELECT A.FLAVOR
FROM FIRST_HALF A JOIN
(
    SELECT FLAVOR, SUM(TOTAL_ORDER) JULY_ORDER
    FROM JULY
    GROUP BY FLAVOR
) B
ON A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + B.JULY_ORDER) DESC
LIMIT 3