SELECT
    ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM
    DEVELOPERS A
WHERE EXISTS(
    SELECT 1
    FROM SKILLCODES B
    WHERE B.CATEGORY = 'Front End'
    AND (A.SKILL_CODE & B.CODE) = B.CODE
)
ORDER BY ID ASC