SELECT
    B.USER_ID AS USER_ID,
    B.NICKNAME AS NICKNAME,
    A.TOTAL_SALES AS TOTAL_SALES
FROM 
(
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
) A JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC
