SELECT
    C. MEMBER_NAME AS MEMBER_NAME,
    A.REVIEW_TEXT AS REVIEW_TEXT,
    A.REVIEW_DATE AS REVIEW_DATE
FROM REST_REVIEW A JOIN
    (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    ) B
ON A.MEMBER_ID = B.MEMBER_ID
JOIN MEMBER_PROFILE C ON
A.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC