SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D JOIN 
(
    SELECT CODE
    FROM SKILLCODES 
    WHERE NAME = 'Python' OR NAME = 'C#'
) C
ON D.SKILL_CODE & C.CODE = C.CODE
ORDER BY D.ID ASC