SELECT A.ID ID, B.FISH_NAME FISH_NAME, A.LENGTH LENGTH
FROM FISH_INFO A JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = (
    SELECT MAX(C.LENGTH)
    FROM FISH_INFO C
    WHERE C.FISH_TYPE = A.FISH_TYPE
)
ORDER BY ID ASC