SELECT 
    DEPT.DEPT_ID,
    DEPT.DEPT_NAME_EN, 
    ROUND(AVG(EMP.SAL),0) AS AVG_SAL
FROM HR_DEPARTMENT AS DEPT JOIN HR_EMPLOYEES AS EMP
ON DEPT.DEPT_ID = EMP.DEPT_ID
GROUP BY DEPT.DEPT_ID
ORDER BY AVG_SAL DESC