SELECT 
    A.CATEGORY AS CATEGORY, 
    SUM(B.SALES) AS TOTAL_SALES
FROM 
    BOOK A JOIN
    (
        SELECT BOOK_ID, SALES
        FROM BOOK_SALES 
        WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    ) B
ON A.BOOK_ID = B.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY ASC