SELECT 
    COUNT(*) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    A.FISH_TYPE AS FISH_TYPE
FROM FISH_INFO A
JOIN (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(
        CASE
            WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH
        END
    ) >= 33
) B ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY A.FISH_TYPE
ORDER BY A.FISH_TYPE ASC
